# numpy
파이썬의 리스트를 대체할 numpy 속도 빠름 C++로 만들어졌음  
cmd 창에 가상환경 들어가서 설정  
conda install numpy

In [4]:
import numpy as np

In [5]:
a1 = np.array([0,1,2,3,4,5])
print(a1)

[0 1 2 3 4 5]


list랑 다른점은 ,가 없다

In [6]:
print(type(a1))

<class 'numpy.ndarray'>


In [7]:
print(a1.dtype) # dtype은 속성을 알수있음, 맥이라 32비트가 아니라 64비트 찍힘

int64


In [8]:
a2 = np.array([0,1,4,5,10,0.5])  #실수 타입이란는 거, numpy 하나에 여러타입을 들어가는것을 허용하지 않는다
print(a2)

[ 0.   1.   4.   5.  10.   0.5]


In [9]:
print(a2.dtype)

float64


### 2차원 list

In [10]:
a3 = np.array([[1,2,3],[4,5,6],[7,8,9]])  #numpy이 2차원 list는 행과 열로 나주어준다.
print(a3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
temp_list = ([[1,2,3],[4,5,6],[7,8,9]])
print(temp_list)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


### arange

In [12]:
a4 = np.arange(0,10,2) #numpy는 range가 아니라 arange로 한다.
print(a4)

[0 2 4 6 8]


In [13]:
a5 =np.arange(1,10)
print(a5)

[1 2 3 4 5 6 7 8 9]


In [14]:
a6 = np.arange(5)
print(a6)

[0 1 2 3 4]


### reshape

In [15]:
a7= np.arange(12).reshape(4,3)
print(a7)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [16]:
print(a7.shape) ##shape를 알고 싶을때는 shape

(4, 3)


In [18]:
a8 = np.arange(11).reshape(4,3)

ValueError: cannot reshape array of size 11 into shape (4,3)

###  linspace


In [19]:
a = np.linspace(1,10,10) # 1부터 10까지 사이를 10개의 구간으로 쪼갠다 , 그래프 만들때 많이 사용한다.

print(a)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [20]:
a = np.linspace(1,10,8) # 1부터 10까지 사이를 8개의 구간으로 쪼갠다
print(a)

[ 1.          2.28571429  3.57142857  4.85714286  6.14285714  7.42857143
  8.71428571 10.        ]


In [21]:
a = np.linspace(1,np.pi,20) # 1부터 np.pi까지 사이를 20개의 구간으로 쪼갠다
print(a)

[1.         1.1127154  1.22543081 1.33814621 1.45086161 1.56357701
 1.67629242 1.78900782 1.90172322 2.01443863 2.12715403 2.23986943
 2.35258483 2.46530024 2.57801564 2.69073104 2.80344645 2.91616185
 3.02887725 3.14159265]


### zeros, ones, eye

In [22]:
a1 = np.zeros(10, int)  # 0으로 채워준다 (항목,타입)
print(a1)
a2 = np.zeros((3, 4), int) # (shape,타입)
print(a2)
a3 = np.ones(5) #ones 1로 채워준다 디폴트는 실수 타입
print(a3)
a4 = np.ones((3, 5)) #((shape))
print(a4)
a5 = np.eye(3) # 단위행열(좌상단에서 우상단으로 주대각이 1이고 나머지 0인 경우)을 eye (단위행렬 기호 : I)
print(a5)

[0 0 0 0 0 0 0 0 0 0]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### 문자열 타입 읽는 법

In [23]:
a1 = np.array(['abc', 'whoami', 'chemistry'])
print(a1)
print(a1.dtype)  # 문자열 타입 읽는 법    <U9    제일긴 놈보다 작다.,유니코드,제일긴 높이9자리

['abc' 'whoami' 'chemistry']
<U9


### astype 변환

In [24]:
a1 = np.array(['1.567', '0.123', '5.232', '5', '8'])
print(a1.dtype)

<U5


In [26]:
num = a1.astype(float) # astype으로 변경 a1은 타입이 변환되지 않고 변환 된것을 출력해준다.
print(num.dtype)

float64


### random

In [27]:
a1 = np.random.rand() # rand가 0~1사이를 램덤하게 찍어준다.
print(a1)

0.17448629919631353


In [28]:
a1 = np.random.rand(2,3) 
print(a1)

[[0.52957992 0.54863176 0.15638135]
 [0.75617984 0.79418924 0.27881849]]


In [29]:
a1 = np.random.rand(2,3,4) 
print(a1)

[[[0.5470765  0.95435497 0.06787311 0.47724108]
  [0.23874965 0.56364438 0.82629561 0.65404172]
  [0.42396918 0.98051809 0.77150868 0.21593737]]

 [[0.80996927 0.78146647 0.33457137 0.60104074]
  [0.7390031  0.81931344 0.78181395 0.18777739]
  [0.6751     0.71961211 0.82656915 0.07690835]]]


In [30]:
a1 = np.random.randint(10,size=(3,4)) # 정수 0~9까지 3바이 4
print(a1)

[[7 3 6 5]
 [1 2 9 5]
 [0 5 2 8]]


In [31]:
a1 = np.random.randint(1,30) # 정수 1~29까지 1개
print(a1)

11


### 항목끼리 사측연산 가능
항목끼리 연산하는것을 element wise 연산  
단, 2개의 shape이 같아야한다.

In [32]:
a1 = np.array([10, 20, 30, 40])  
a2 = np.array([1, 2, 3, 4])
print(a1 + a2)
print(a1 - a2)
print(a1 * 2)
print(a1 ** 2)
print(a1 * a2)
print(a1 / a2)
print(a1 / (a2 ** 2))
print(a1 > 20)

[11 22 33 44]
[ 9 18 27 36]
[20 40 60 80]
[ 100  400  900 1600]
[ 10  40  90 160]
[10. 10. 10. 10.]
[10.          5.          3.33333333  2.5       ]
[False False  True  True]


### 기본적인 수학함수 지원

In [33]:
a1 = np.arange(1, 6)
print(a1)
print(a1.sum())
print(a1.mean()) # 평균
print(a1.std())  # 표존편차
print(a1.var())  # 분산
print(a1.min())
print(a1.max())
print(a1.cumsum())  # 누적 합계
print(a1.cumprod()) # 누적 곱

[1 2 3 4 5]
15
3.0
1.4142135623730951
2.0
1
5
[ 1  3  6 10 15]
[  1   2   6  24 120]


### 선형 대수학을 지원해서 행렬도 지원

In [34]:
## NumPy는 선형 대수(Linear Algebra)를 위한 행렬 연산을 지원

a = np.array([0, 1, 2, 3]).reshape(2, 2)
print(a)

b = np.array([3, 2, 0, 1]).reshape(2, 2)
print(b)
print('-'*20)
print(a.dot(b)) # 행렬곲
print(np.dot(a, b)) # 행렬곲
print('-'*20)
print(np.transpose(a)) # 전치행렬
print(a.transpose()) # 전치행렬
print('-'*20)
print(np.linalg.inv(a)) # 역행렬
print(np.linalg.det(a)) # 행렬식

[[0 1]
 [2 3]]
[[3 2]
 [0 1]]
--------------------
[[0 1]
 [6 7]]
[[0 1]
 [6 7]]
--------------------
[[0 2]
 [1 3]]
[[0 2]
 [1 3]]
--------------------
[[-1.5  0.5]
 [ 1.   0. ]]
-2.0


### 인데씽 지원

In [35]:
a = np.array([0,10,20,30,40,50])  ## 인데싱 지원
print(a[0])
print(a[4])

0
40


In [36]:
print(a[[1,3,4]])

[10 30 40]


In [37]:
a, b, c = a[[1,3,4]]
print(a,b,c)

10 30 40


In [38]:
b = np.arange(10, 100, 10).reshape(3, 3)
print(b)
print(b[0, 2])  
b[2, 2] = 97  
print(b)
print(b[1])
print('-'*20)
b[1] = np.array([45, 55, 65])
print(b)
b[2] = [75, 85, 95]
print(b)
print('-'*20)
print(b[[0, 2], [0, 1]])

[[10 20 30]
 [40 50 60]
 [70 80 90]]
30
[[10 20 30]
 [40 50 60]
 [70 80 97]]
[40 50 60]
--------------------
[[10 20 30]
 [45 55 65]
 [70 80 97]]
[[10 20 30]
 [45 55 65]
 [75 85 95]]
--------------------
[10 85]


In [106]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a[a > 3])
print(a[(a % 2) == 0])

[4 5 6]
[2 4 6]


### 슬라이씽   
파이썬 기본적문법 먹음

In [108]:
a = np.array([0, 10, 20, 30, 40, 50])
print(a[1:4])
print(a[:3])
print(a[2:])
a[2:5] = np.array([25, 35, 45])
print(a)

[10 20 30]
[ 0 10 20]
[20 30 40 50]
[ 0 10 25 35 45 50]


In [109]:
a = np.arange(10, 100, 10).reshape(3, 3)
print(a)
print(a[1:3, 1:3])
print(a[:3, 1:])
print(a[1][0:2])
a[0:2, 1:3] = np.array([[25, 35], [55, 65]])
print(a)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
[[50 60]
 [80 90]]
[[20 30]
 [50 60]
 [80 90]]
[40 50]
[[10 25 35]
 [40 55 65]
 [70 80 90]]
